name: Auto Update & Deploy

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages(c("tidyverse", "httr", "jsonlite", "quarto"))'

      - name: Run Data Extraction Script
        run: Rscript scripts/extract_stock_data.R

      - name: Commit & Push Updated Data
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add data/ || echo "No changes to add"
          git diff --staged --quiet || git commit -m "Automated data update" || echo "No changes to commit"
          git push origin main || echo "No changes to push"

  deploy_dashboard:
    runs-on: ubuntu-latest
    needs: update_data
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Dashboard
        run: quarto render dashboard/halal_stocks.qmd

      - name: Render Quarto Website
        run: |
          quarto render dashboard

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
         personal_token: ${{ secrets.GH_PAT }}
        publish_dir: _site

